version: '3.9'

services:
  web:
    build: .
    image: ivansomkin/django-library-tutorial_web
    volumes:
      - .:/code
      - staticfiles:/code/static
  web_migrate:
    image: ivansomkin/django-library-tutorial_web_migrate
    extends:
      service: web
    command: python manage.py migrate
  web_run:
    image: ivansomkin/django-library-tutorial_web_run
    extends:
      service: web
    command: gunicorn locallibrary.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
  nginx:
    image: nginx
    depends_on:
      - web_run
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
      - staticfiles:/var/www/html/static
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  staticfiles:
