name: Docker Deployment Automation

on: 
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest    
    
    steps:
      - uses: actions/checkout@v1

  cd:
    runs-on: ubuntu-latest
    needs: ci
    environment: Docker
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Run
        run: |
          docker-compose up -d
          kill -2 
      
      - name: Test
        run: docker-compose exec web_run python3.8 manage.py test --no-input
      
      - name: Stop
        run: docker-compose stop
      
      - name: Tag
        run: |
          docker tag ${{ secrets.DOCKER_USER }}/django-library-tutorial_web ${{ secrets.DOCKER_USER }}/django-library-tutotial_web:${{ github.sha }}  
          docker tag ${{ secrets.DOCKER_USER }}/django-library-tutorial_web ${{ secrets.DOCKER_USER }}/django-library-tutotial_web:latest
          docker tag ${{ secrets.DOCKER_USER }}/django-library-tutorial_web_migrate ${{ secrets.DOCKER_USER }}/django-library-tutotial_web_migrate:${{ github.sha }}  
          docker tag ${{ secrets.DOCKER_USER }}/django-library-tutorial_web_migrate ${{ secrets.DOCKER_USER }}/django-library-tutotial_web_migrate:latest
          docker tag ${{ secrets.DOCKER_USER }}/django-library-tutorial_web_run ${{ secrets.DOCKER_USER }}/django-library-tutotial_web_run:${{ github.sha }}  
          docker tag ${{ secrets.DOCKER_USER }}/django-library-tutorial_web_run ${{ secrets.DOCKER_USER }}/django-library-tutotial_web_run:latest
 
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/django-library-tutotial_web:${{ github.sha }}  
          docker push ${{ secrets.DOCKER_USER }}/django-library-tutotial_web:latest
          docker push ${{ secrets.DOCKER_USER }}/django-library-tutotial_web_migrate:${{ github.sha }}  
          docker push ${{ secrets.DOCKER_USER }}/django-library-tutotial_web_migrate:latest
          docker push ${{ secrets.DOCKER_USER }}/django-library-tutotial_web_run:${{ github.sha }}  
          docker push ${{ secrets.DOCKER_USER }}/django-library-tutotial_web_run:latest
